import type { Metadata } from "next";

import "./globals.css";
export const metadata: Metadata = {
  title: "Emtek Career & Education Festival 2023",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="relative overflow-hidden">

        {children} 
        </main>
        
      </body>
    </html>
  );
}
